### ISSUE TITLE
The number of layers to be downloaded is wrong

### ISSUE THREAD

**Issue by gullitmiranda** [azukiapp/docker-registry-downloader#4]
The `docker-registry-downloader` is displaying the total number of layers and not the number of layers to be downloaded.

![image](https://cloud.githubusercontent.com/assets/2034678/5863434/b35932f0-a260-11e4-8a3f-531211e36d7d.png)

**Comment by saitodisse** [comment]
I've included a test to see if the layers are being verified correctly.
Apparently the check is ok.

**Comment by nuxlli** [comment]
I do not know if the tests resolves the issue, since the number of layers of an image can be different from the number of layers that I will download if I already have of them in my instance of the current Docker.

**Comment by saitodisse** [comment]
As long nothing changes in docker registry the test will work. The stub is on local docker remote. What I do is a diff.
